// Helper to safely get DOM elements with type assertion
export function getElement<T extends Element = HTMLElement>(id: string): T {
  const el = document.getElementById(id)
  if (!el) throw new Error(`Element #${id} not found`)
  return el as unknown as T
}

// Shared DOM elements mappings
export const elements = {
  widgetContainer: getElement<HTMLDivElement>('widgetContainer'),
  titleBar: getElement<HTMLDivElement>('titleBar'),
  loadingContainer: getElement<HTMLDivElement>('loadingContainer'),
  loginContainer: getElement<HTMLDivElement>('loginContainer'),
  noUsageContainer: getElement<HTMLDivElement>('noUsageContainer'),
  mainContent: getElement<HTMLDivElement>('mainContent'),
  loginStep1: getElement<HTMLDivElement>('loginStep1'),
  loginStep2: getElement<HTMLDivElement>('loginStep2'),
  autoDetectBtn: getElement<HTMLButtonElement>('autoDetectBtn'),
  autoDetectError: getElement<HTMLParagraphElement>('autoDetectError'),
  openBrowserLink: getElement<HTMLAnchorElement>('openBrowserLink'),
  nextStepBtn: getElement<HTMLButtonElement>('nextStepBtn'),
  backStepBtn: getElement<HTMLButtonElement>('backStepBtn'),
  sessionKeyInput: getElement<HTMLInputElement>('sessionKeyInput'),
  connectBtn: getElement<HTMLButtonElement>('connectBtn'),
  sessionKeyError: getElement<HTMLParagraphElement>('sessionKeyError'),
  refreshBtn: getElement<HTMLButtonElement>('refreshBtn'),
  minimizeBtn: getElement<HTMLButtonElement>('minimizeBtn'),
  closeBtn: getElement<HTMLButtonElement>('closeBtn'),

  sessionPercentage: getElement<HTMLSpanElement>('sessionPercentage'),
  sessionProgress: getElement<HTMLDivElement>('sessionProgress'),
  sessionTimer: getElement<SVGCircleElement>('sessionTimer'),
  sessionTimeText: getElement<HTMLDivElement>('sessionTimeText'),
  sessionUsageRing: getElement<SVGCircleElement>('sessionUsageRing'),

  weeklyPercentage: getElement<HTMLSpanElement>('weeklyPercentage'),
  weeklyProgress: getElement<HTMLDivElement>('weeklyProgress'),
  weeklyTimer: getElement<SVGCircleElement>('weeklyTimer'),
  weeklyTimeText: getElement<HTMLDivElement>('weeklyTimeText'),
  weeklyUsageRing: getElement<SVGCircleElement>('weeklyUsageRing'),

  sonnetRow: getElement<HTMLDivElement>('sonnetRow'),
  sonnetPercentage: getElement<HTMLSpanElement>('sonnetPercentage'),
  sonnetProgress: getElement<HTMLDivElement>('sonnetProgress'),
  sonnetTimer: getElement<SVGCircleElement>('sonnetTimer'),
  sonnetTimeText: getElement<HTMLDivElement>('sonnetTimeText'),

  statusBar: getElement<HTMLDivElement>('statusBar'),
  statusText: getElement<HTMLSpanElement>('statusText'),
  graphToggleBtn: getElement<HTMLButtonElement>('graphToggleBtn'),
  graphSection: getElement<HTMLDivElement>('graphSection'),
  usageChart: getElement<HTMLCanvasElement>('usageChart'),

  pieToggleBtn: getElement<HTMLButtonElement>('pieToggleBtn'),
  pieSection: getElement<HTMLDivElement>('pieSection'),
  pieChart: getElement<HTMLCanvasElement>('pieChart'),
  extraUsageToggleBtn: getElement<HTMLButtonElement>('extraUsageToggleBtn'),

  expandSection: getElement<HTMLDivElement>('expandSection'),
  extraRows: getElement<HTMLDivElement>('extraRows'),

  settingsBtn: getElement<HTMLButtonElement>('settingsBtn'),
  settingsOverlay: getElement<HTMLDivElement>('settingsOverlay'),
  settingsContent: getElement<HTMLDivElement>('settingsContent'),
  closeSettingsBtn: getElement<HTMLButtonElement>('closeSettingsBtn'),
  logoutBtn: getElement<HTMLButtonElement>('logoutBtn'),
  clearHistoryBtn: getElement<HTMLButtonElement>('clearHistoryBtn'),
  coffeeBtn: getElement<HTMLButtonElement>('coffeeBtn'),
  coffeeBtnAlt: getElement<HTMLButtonElement>('coffeeBtnAlt'),
  refreshIntervalSlider: getElement<HTMLInputElement>('refreshIntervalSlider'),
  refreshIntervalValue: getElement<HTMLSpanElement>('refreshIntervalValue'),
  autoStartSection: getElement<HTMLDivElement>('autoStartSection'),
  autoStartToggle: getElement<HTMLInputElement>('autoStartToggle'),
  themeDropdown: getElement<HTMLSelectElement>('themeDropdown'),
  backgroundHueDropdown: getElement<HTMLSelectElement>('backgroundHueDropdown'),

  // Codex
  codexSection: getElement<HTMLDivElement>('codexSection'),
  codexLoginContainer: getElement<HTMLDivElement>('codexLoginContainer'),
  codexContent: getElement<HTMLDivElement>('codexContent'),
  codexAutoDetectBtn: getElement<HTMLButtonElement>('codexAutoDetectBtn'),
  codexManualBtn: getElement<HTMLButtonElement>('codexManualBtn'),
  codexManualInput: getElement<HTMLDivElement>('codexManualInput'),
  codexTokenInput: getElement<HTMLInputElement>('codexTokenInput'),
  codexSaveBtn: getElement<HTMLButtonElement>('codexSaveBtn'),
  codexTokenError: getElement<HTMLParagraphElement>('codexTokenError'),
  codexBackBtn: getElement<HTMLButtonElement>('codexBackBtn'),
  codexLoginError: getElement<HTMLParagraphElement>('codexLoginError'),
  codexStatusText: getElement<HTMLSpanElement>('codexStatusText'),
  codexGraphToggleBtn: getElement<HTMLButtonElement>('codexGraphToggleBtn'),
  codexGraphSection: getElement<HTMLDivElement>('codexGraphSection'),
  codexUsageChart: getElement<HTMLCanvasElement>('codexUsageChart'),
  codexPieToggleBtn: getElement<HTMLButtonElement>('codexPieToggleBtn'),
  codexPieSection: getElement<HTMLDivElement>('codexPieSection'),
  codexPieChart: getElement<HTMLCanvasElement>('codexPieChart'),

  codexSessionProgress: getElement<HTMLDivElement>('codexSessionProgress'),
  codexSessionPercentage: getElement<HTMLSpanElement>('codexSessionPercentage'),
  codexSessionTimer: getElement<SVGCircleElement>('codexSessionTimer'),
  codexSessionTimeText: getElement<HTMLDivElement>('codexSessionTimeText'),
  codexSessionUsageRing: getElement<SVGCircleElement>('codexSessionUsageRing'),

  codexWeeklyProgress: getElement<HTMLDivElement>('codexWeeklyProgress'),
  codexWeeklyPercentage: getElement<HTMLSpanElement>('codexWeeklyPercentage'),
  codexWeeklyTimer: getElement<SVGCircleElement>('codexWeeklyTimer'),
  codexWeeklyTimeText: getElement<HTMLDivElement>('codexWeeklyTimeText'),
  codexWeeklyUsageRing: getElement<SVGCircleElement>('codexWeeklyUsageRing'),

  // Copilot
  copilotSection: getElement<HTMLDivElement>('copilotSection'),
  copilotLoginContainer: getElement<HTMLDivElement>('copilotLoginContainer'),
  copilotContent: getElement<HTMLDivElement>('copilotContent'),
  copilotLoginPrompt: getElement<HTMLDivElement>('copilotLoginPrompt'),
  copilotConnectBtn: getElement<HTMLButtonElement>('copilotConnectBtn'),
  copilotLoginError: getElement<HTMLParagraphElement>('copilotLoginError'),
  copilotClientIdSetup: getElement<HTMLDivElement>('copilotClientIdSetup'),
  copilotClientIdInput: getElement<HTMLInputElement>('copilotClientIdInput'),
  copilotClientIdSaveBtn: getElement<HTMLButtonElement>('copilotClientIdSaveBtn'),
  copilotClientIdError: getElement<HTMLParagraphElement>('copilotClientIdError'),
  copilotClientIdBackBtn: getElement<HTMLButtonElement>('copilotClientIdBackBtn'),
  copilotDeviceFlow: getElement<HTMLDivElement>('copilotDeviceFlow'),
  copilotUserCode: getElement<HTMLDivElement>('copilotUserCode'),
  copilotOpenGithubBtn: getElement<HTMLButtonElement>('copilotOpenGithubBtn'),
  copilotCancelFlowBtn: getElement<HTMLButtonElement>('copilotCancelFlowBtn'),
  copilotWaitingText: getElement<HTMLParagraphElement>('copilotWaitingText'),
  copilotPlanSubtitle: getElement<HTMLSpanElement>('copilotPlanSubtitle'),
  copilotPremiumProgress: getElement<HTMLDivElement>('copilotPremiumProgress'),
  copilotPremiumPercentage: getElement<HTMLSpanElement>('copilotPremiumPercentage'),
  copilotCountText: getElement<HTMLDivElement>('copilotCountText'),
  copilotStatusText: getElement<HTMLSpanElement>('copilotStatusText'),
  copilotResetText: getElement<HTMLSpanElement>('copilotResetText'),

  // Gemini
  geminiSection: getElement<HTMLDivElement>('geminiSection'),
  geminiLoginContainer: getElement<HTMLDivElement>('geminiLoginContainer'),
  geminiContent: getElement<HTMLDivElement>('geminiContent'),
  geminiApiKeyInput: getElement<HTMLInputElement>('geminiApiKeyInput'),
  geminiSaveBtn: getElement<HTMLButtonElement>('geminiSaveBtn'),
  geminiLoginError: getElement<HTMLParagraphElement>('geminiLoginError'),
  geminiStatusText: getElement<HTMLSpanElement>('geminiStatusText'),
  geminiDailyProgress: getElement<HTMLDivElement>('geminiDailyProgress'),
  geminiDailyPercentage: getElement<HTMLSpanElement>('geminiDailyPercentage'),
  geminiDailyUsageRing: getElement<SVGCircleElement>('geminiDailyUsageRing'),
  geminiDailyTimer: getElement<SVGCircleElement>('geminiDailyTimer'),
  geminiDailyTimeText: getElement<HTMLDivElement>('geminiDailyTimeText'),
}